### ISSUE TITLE
[Article] Multiverse

### ISSUE THREAD

**Issue by just-a-random-person** [Billy-Bloom/BloomDocs#21]
**What is the purpose of the article you are suggesting?**
Ex: I would like an article on how to set up the Multiverse-Core spigot plugin.
I'm gonna go ahead and use my example here, think a multiverse tutorial is a good idea.
**Are you willing to write this article?**
Yes
**Additional info**
Add any other info or screenshots about the feature request here.
https://dev.bukkit.org/projects/multiverse-core

**Comment by nickpdx** [comment]
There's already a tutorial on Multiverse https://docs.bloom.host/plugins/multiverse - you're free to propose any changes in a pull request though.

**Comment by just-a-random-person** [comment]
oh god i didn’t see it.
