### ISSUE TITLE
[Typo] Spanish articles have images with english text and old logo

### ISSUE THREAD

**Issue by just-a-random-person** [Billy-Bloom/BloomDocs#25]
**Describe the typo**
A clear and concise description of what the typo is.
Spanish articles have images with english text and old logo, should be bloom.host and text should be in spanish for spanish articles
**To Reproduce**
Please include a screenshot of the typo, as well as a link to the page with the typo.
https://docs.bloom.host/languages/spanish/basico/panel/controles-basicos

**Comment by just-a-random-person** [comment]
possibly just remove the images as they aren't in english version of article

**Comment by nickpdx** [comment]
> 
> possibly just remove the images as they aren't in english version of article

This seems like the best option, IMO articles don't really need a fancy image.

**Comment by just-a-random-person** [comment]
I'll make a PR

**Comment by LoJoSho** [comment]
Closed from @just-a-random-person PR #34 which fixed this.
