### ISSUE TITLE
[Incorrect Link] Update Pl3xMap invite link

### ISSUE THREAD

**Issue by Encode42** [Billy-Bloom/BloomDocs#96]
**Describe the issue**
The link to Pl3xMap's Discord has changed since the project separated from Purpur's Discord.

**To Reproduce**
[Docs Page](https://docs.bloom.host/plugins/pl3xmap/)

![](https://user-images.githubusercontent.com/34699884/120033778-0ef26e00-bfca-11eb-9a9f-d0baad4eb6c7.jpeg)

**Expected link**
https://discord.gg/B8WpDPXeBh

**Comment by Billy-Bloom** [comment]
Thanks! Updated
